
spring:
  application:
    name: interview-api-database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hire_with_code
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true









